name: Build and deploy to npm

on:
  push:
    branches:
      - master
      - 'environment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          scope: '@EDMdesigner'
          registry-url: 'https://npm.pkg.github.com/'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GH_PACKAGES }}
      - run: npm test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
 