name: Build and deploy to npm

on:
  push:
    branches:
      - master
      - 'environment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@EDMdesigner'
          NODE_AUTH_TOKEN: ${{secrets.NPM_GH_PACKAGES}}
      - run: npm ci
      # - run: npm test
      - run: npm run build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
 
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
