name: Build and deploy to npm

on:
  push:
    branches:
      - master
      - 'environment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@EDMdesigner'
      - run: npm ci
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_GH_PACKAGES}}
      - run: npm test
 
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
